# Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [225]:
import pandas as pd

In [226]:
data=[10,20,30,40,50]
ser=pd.Series(data)
print(ser)

0    10
1    20
2    30
3    40
4    50
dtype: int64

# Write a Python program to convert a Panda module Series to Python list and it's type.

In [227]:
data = [10, 20, 30, 40, 50]
series = pd.Series(data)

python_list = series.tolist()
print(python_list)

[10, 20, 30, 40, 50]

# Write a Python program to add, subtract, multiple and divide two Pandas Series.Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [228]:
se=pd.Series([2,4,6,8,10])
ser=pd.Series([1,3,5,7,9])
add=se+ser
sub=se-ser
mul=se*ser
div=se/ser
print(add)
print(sub)
print(mul)
print(div)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

# Write a Python program to get the powers of an array values element-wise.Note: First array elements raised to powers from second array

In [229]:
s1=pd.Series([0,1,2,3,4,5,6])
s2=pd.Series([3,3,3,3,3,3,3])
s3=s1**s2
s3

0      0
1      1
2      8
3     27
4     64
5    125
6    216
dtype: int64

# Write a Python program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [230]:
exam_data=pd.DataFrame({
'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, None, 9, 20, 14.5, None, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
})
exam_data
dt=pd.Series(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
exam_data.set_index(dt,inplace=True)
exam_data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

# Write a Python program to display a summary of the basic information about a specified Data Frame and its data.

In [231]:
exam_data.info()

<class 'pandas.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     str
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 400.0+ bytes

In [232]:
exam_data.describe()

           score   attempts
count   8.000000  10.000000
mean   13.562500   1.900000
std     4.693746   0.875595
min     8.000000   1.000000
25%     9.000000   1.000000
50%    13.500000   2.000000
75%    17.125000   2.750000
max    20.000000   3.000000

# Write a Python program to get the first 3 rows of a given DataFrame. Sample Python dictionary data and list labels:

In [233]:
exam_data.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

# Write a Python program to select the 'name' and 'score' columns from the following DataFrame.

In [234]:
exam_data[['name','score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

In [235]:
exam_data.loc[['a','c','i','j'],['name','score']]

        name  score
a  Anastasia   12.5
c  Katherine   16.5
i      Kevin    8.0
j      Jonas   19.0

In [236]:
exam_data.iloc[[1,3,5,6],[0,1]]

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

# Write a Python program to select the rows where the number of attempts in the examination is greater than 2.

In [237]:
exam_data[exam_data['attempts']>2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

# Write a Python program to count the number of rows and columns of a DataFrame.Sample data:

In [238]:
print(len(exam_data.index))
print(len(exam_data.columns))

10
4

# Write a Python program to select the rows where the score is missing, i.e. is NaN.

In [239]:
exam_data[exam_data['score'].isnull()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

# Write a Python program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [240]:
exam_data[(exam_data['attempts']<2) & (exam_data['score']>15)]

    name  score  attempts qualify
j  Jonas   19.0         1     yes

# Write a Python program to change the score in row 'd' to 11.5.

In [241]:
exam_data.loc['d','score']=11.5
exam_data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [242]:
exam_data.at['d','score']=15.5
exam_data

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   15.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

# Write a Python program to calculate the sum of the examination attempts by the students.

In [243]:
exam_data['attempts'].sum()

np.int64(19)

# Write a Python program to calculate the mean score for each different student in DataFrame.

In [244]:
exam_data.groupby('name')['score'].mean()

name
Anastasia    12.5
Dima          9.0
Emily         9.0
James        15.5
Jonas        19.0
Katherine    16.5
Kevin         8.0
Laura         NaN
Matthew      14.5
Michael      20.0
Name: score, dtype: float64

# Write a Python program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame.

In [245]:
exam_data.loc['k']=['suresh','15.5','1','Yes']
exam_data

        name score attempts qualify
a  Anastasia  12.5        1     yes
b       Dima   9.0        3      no
c  Katherine  16.5        2     yes
d      James  15.5        3      no
e      Emily   9.0        2      no
f    Michael  20.0        3     yes
g    Matthew  14.5        1     yes
h      Laura   NaN        1      no
i      Kevin   8.0        2      no
j      Jonas  19.0        1     yes
k     suresh  15.5        1     Yes

In [246]:
exam_data=exam_data.drop('k')
exam_data

        name score attempts qualify
a  Anastasia  12.5        1     yes
b       Dima   9.0        3      no
c  Katherine  16.5        2     yes
d      James  15.5        3      no
e      Emily   9.0        2      no
f    Michael  20.0        3     yes
g    Matthew  14.5        1     yes
h      Laura   NaN        1      no
i      Kevin   8.0        2      no
j      Jonas  19.0        1     yes

# Write a Python program to sort the DataFrame first by 'name' in descending order,then by 'score' in ascending order.

In [247]:
exam_data = exam_data.sort_values(by=['name', 'score'], ascending=[False, True])
exam_data

        name score attempts qualify
f    Michael  20.0        3     yes
g    Matthew  14.5        1     yes
h      Laura   NaN        1      no
i      Kevin   8.0        2      no
c  Katherine  16.5        2     yes
j      Jonas  19.0        1     yes
d      James  15.5        3      no
e      Emily   9.0        2      no
b       Dima   9.0        3      no
a  Anastasia  12.5        1     yes

# Write a Python program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

In [249]:
exam_data['qualify'] = exam_data['qualify'].replace({'yes': True, 'no': False})
exam_data

        name score attempts qualify
f    Michael  20.0        3    True
g    Matthew  14.5        1    True
h      Laura   NaN        1   False
i      Kevin   8.0        2   False
c  Katherine  16.5        2    True
j      Jonas  19.0        1    True
d      James  15.5        3   False
e      Emily   9.0        2   False
b       Dima   9.0        3   False
a  Anastasia  12.5        1    True

# Write a Python program to delete the 'attempts' column from the DataFrame.

In [251]:
exam_data.drop(columns='attempts')

        name score qualify
f    Michael  20.0    True
g    Matthew  14.5    True
h      Laura   NaN   False
i      Kevin   8.0   False
c  Katherine  16.5    True
j      Jonas  19.0    True
d      James  15.5   False
e      Emily   9.0   False
b       Dima   9.0   False
a  Anastasia  12.5    True

# Write a Python program to insert a new column in existing DataFrame.

In [252]:
exam_data['attempts']=[1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
exam_data

        name score  attempts qualify
f    Michael  20.0         1    True
g    Matthew  14.5         3    True
h      Laura   NaN         2   False
i      Kevin   8.0         3   False
c  Katherine  16.5         2    True
j      Jonas  19.0         3    True
d      James  15.5         1   False
e      Emily   9.0         1   False
b       Dima   9.0         2   False
a  Anastasia  12.5         1    True

# Write a Python program to iterate over rows in a DataFrame.

In [254]:
for index, row in exam_data.iterrows():
    print("Index:", index)
    print("Name:", row['name'], "Score:", row['score'],"attempts",row['attempts'])
    print("------")

Index: f
Name: Michael Score: 20.0 attempts 1
------
Index: g
Name: Matthew Score: 14.5 attempts 3
------
Index: h
Name: Laura Score: nan attempts 2
------
Index: i
Name: Kevin Score: 8.0 attempts 3
------
Index: c
Name: Katherine Score: 16.5 attempts 2
------
Index: j
Name: Jonas Score: 19.0 attempts 3
------
Index: d
Name: James Score: 15.5 attempts 1
------
Index: e
Name: Emily Score: 9.0 attempts 1
------
Index: b
Name: Dima Score: 9.0 attempts 2
------
Index: a
Name: Anastasia Score: 12.5 attempts 1
------

# Write a Python program to get list from DataFrame column headers.

In [255]:
column_list = exam_data.columns.tolist()
column_list

['name', 'score', 'attempts', 'qualify']