In [48]:
import pandas as pd

In [49]:
pd.__version__

'3.0.1'

In [50]:
# series

sales=pd.Series([1,2,3,0])
sales

0    1
1    2
2    3
3    0
dtype: int64

In [51]:
p=sales[0]
p

np.int64(1)

In [52]:
sales[0:2:]

0    1
1    2
dtype: int64

In [53]:
sales.index

RangeIndex(start=0, stop=4, step=1)

In [54]:
sales.values

array([1, 2, 3, 0])

In [55]:
sales.dtype

dtype('int64')

In [56]:
sales.head(2)

0    1
1    2
dtype: int64

In [57]:
sales.tail(1)

3    0
dtype: int64

In [58]:
sales.sort_values()

3    0
0    1
1    2
2    3
dtype: int64

In [59]:
sales.count()

np.int64(4)

In [60]:
sales.isnull()

0    False
1    False
2    False
3    False
dtype: bool

In [61]:
sales.notnull()

0    True
1    True
2    True
3    True
dtype: bool

In [62]:
sales + 1

0    2
1    3
2    4
3    1
dtype: int64

In [63]:
sales *2

0    2
1    4
2    6
3    0
dtype: int64

In [65]:
s=pd.Series([1,None,5])
s.isnull()

0    False
1     True
2    False
dtype: bool

In [68]:
k=s.fillna(0)
k

0    1.0
1    0.0
2    5.0
dtype: float64

In [69]:
s1=pd.Series(data=[100,200,300,400,500],index=list('abcde'))
s1

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [71]:
data=pd.DataFrame({
    'Name':['Anna','Ben'],
    'Lemonades':[2,3]
})
data

   Name  Lemonades
0  Anna          2
1   Ben          3

In [73]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
data=pd.DataFrame({'C1':s1 , 'C2':s2})
data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [74]:
data.shape

(5, 2)

In [75]:
data.columns

Index(['C1', 'C2'], dtype='str')

In [76]:
data.dtypes

C1    int64
C2    int64
dtype: object

In [84]:
# using labels
data.loc[1,'C1']

#using index
data.iloc[1,0]

np.int64(2)

In [ ]:
#data information
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int64
 1   C2      5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes

In [ ]:
# data describe
data.describe()

             C1         C2
count  5.000000   5.000000
mean   3.000000  30.000000
std    1.581139  15.811388
min    1.000000  10.000000
25%    2.000000  20.000000
50%    3.000000  30.000000
75%    4.000000  40.000000
max    5.000000  50.000000

In [ ]:
# Filtering
data[data['C1']>=2]

   C1  C2
1   2  20
2   3  30
3   4  40
4   5  50

In [ ]:
# add newcolumn
data['Tips']=[10,20,30,40,40]
data

   C1  C2  Tips
0   1  10    10
1   2  20    20
2   3  30    30
3   4  40    40
4   5  50    40

In [96]:
#updating
data.loc[data['C1']==4]=10
data

   C1  C2  Tips
0   1  10    10
1  10  10    10
2   3  30    30
3  10  10    10
4   5  50    40

In [100]:
data.rename(columns={"C1":"column1"},inplace=True)
data

   column1  C2  Tips
0        1  10    10
1       10  10    10
2        3  30    30
3       10  10    10
4        5  50    40

In [104]:
data.set_index('C2',inplace=True)

In [105]:
data

    Tips
C2
10    10
10    10
30    30
10    10
50    40